###
POST http://localhost:8080/pets
Content-Type: application/json

{
  "name": "Jacky"
}

###
GET http://localhost:8080/pets

###
GET http://localhost:8080/pets/1
Accept: application/json
Content-Type: application/json


